project/models/usuario.py
class Usuario:
    def __init__(self,id, nome, senha):
        self.id= id
        self.nome = nome
        self.senha = senha

lista_usuarios=[]
user= Usuario(2, "igor", "1234")
admin= Usuario(1, "admin", "admin")
lista_usuarios.append(user)
lista_usuarios.append(admin)

project/app.py
from flask import Flask, render_template
from controllers.controller import loginController

app = Flask (__name__)
app.secret_key = 'sua_chave_secreta'

app.register_blueprint(loginController)

@app.errorhandler(404) #erro de pagina não encontrada
def erro404(e):
    return render_template('404.html'), 404

@app.errorhandler(401) #erro de pagina não autorizada
def erro404(e):
    return render_template('401.html'), 401

@app.errorhandler(403) #acesso negado
def page_not_found(e):
    return render_template('403.html'), 403

@app.errorhandler(500)  #erro interno no servidor
def page_not_found(e):
    return render_template('500.html'), 500

if __name__  == '__main__':
    app.run(debug=True)

project/controllers/controller.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash, abort, make_response
from models.usuario import lista_usuarios

loginController = Blueprint('login', __name__)

@loginController.route("/")
def inicial():
    return render_template("index.html")

@loginController.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        nome = request.form.get('nome') #usa o 'name' do input pra pegar a informação do formulario
        senha = request.form.get('senha')
        for usuario in lista_usuarios:
            if usuario.nome == nome and usuario.senha == senha: #criar a session quando o usuario acertar o login, depois da validação
                session['iduser']= usuario.id
                return redirect(url_for('login.dashboard'))
        flash("credenciais invalidas", 'error')     
        flash("tente novamente", 'info')   
    return render_template("login.html")

rotas_publicas = ["login.login", "login.index"]

@loginController.before_request #middleware (hooks)
def verificaLogin():
    print(1)
    if request.endpoint=='login.login' and 'iduser' in session:
        return redirect(url_for('login.index'))
    print(2)
    if request.endpoint in rotas_publicas:
        return 
    print(3)
    if "iduser" not in session: #verifica se o user ta na sessão
        return redirect(url_for('login.login'))
    print(4)
    return

@loginController.route('/dashboard')
def dashboard():
        return render_template('dash.html')  

@loginController.route('/logout')
def logout():
    response=make_response(redirect(url_for("login.login")))
    session.pop("iduser", None) 
    response.set_cookie('nome', '', expires=0)
    response.set_cookie('senha', '', expires=0)
    return response

@loginController.route("/admin")
def admin():
    if session.get("iduser") != 1:
        abort(401)
    return render_template('admin.html')

@loginController.route("/cookie")   
def cookies():
    if request.method == 'POST':
        nome = request.form['nome']
        senha = request.form['senha']
        response=make_response(render_template('fim.html')) 
        if nome == lista_usuarios:
            response.set_cookie('nome', 'Correto', max_age=60 * 60 *24)
        else:
            response.set_cookie('nome', 'Incorreto', max_age=60 * 60 *24)

        if senha == lista_usuarios:
            response.set_cookie('senha', 'Correto', max_age=60 * 60 *24)
        else: 
            response.set_cookie('senha', 'Incorreto', max_age=60 * 60 *24)
        return response
    return render_template('login.html')

project/templates/401.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error 401</title>
</head>
<body>
    NÃO AUTORIZADO
</body>
</html>

project/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='admin.css') }}" media="screen" />
    <title>Admin</title>
</head>
<body>
    <div class="container">
        <h2>Administrador</h2>
        <a href="{{ url_for('login.login') }}"><button type="button">Sair</button></a>
    </div>
</body>
</html>

project/templates/dash.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <div class="container">
        <h2>Você está logado</h2>
        <a href="{{ url_for('login.logout') }}"><button type="button">Logout</button></a>
    </div>
</body>
</html>

project/templates/fim.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fim</title>
</head>
<body>
    <h2>Nome</h2>
    <p>{{request.cookies.get("nome")}}</p>
    <h2>Senha</h2>
    <p>{{request.cookies.get("senha")}}</p>
</body>
</html>

project/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Inicial</title>
</head>
<body>
    <div class="container">
        <h2>Página Inicial</h2>
        {% if session.get("iduser") %}
            <a href="{{ url_for('login.logout') }}"><button type="button">Logout</button></a>
        {% else %}
            <a href="{{ url_for('login.login') }}"><button type="button">Login</button></a>
        {% endif %}
    </div>
</body>
</html>

project/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form action="/login" method="POST">
        <div class="container">
            <h2>Login</h2>
            <input type="text" name='nome' placeholder="Usuário" required>
            <input type="password" name='senha' placeholder="Senha" required>
            <button type="submit">Entrar</button>
            {% with resposta=get_flashed_messages(with_categories = True) %}
                {%if resposta%}
                    {% for category, message in resposta %}
                        <p class="{{category}}">{{message}}</p>
                    {% endfor %}
                {%endif%}
            {% endwith %}
        </div>
    </form>
</body>

</html>